Backend/.gitignore, Backend/package.json, Backend/src/app.ts, Backend/src/controller/hotel_controller.ts, Backend/src/domain/hotel_domain.ts, Backend/src/model/city.ts, Backend/src/model/hotel.ts, Backend/src/model/image.ts, Backend/src/model/state.ts, Backend/src/model/users.ts, Backend/src/package.json
feat(mongoose table schema jul 8) : adding hotel , city , state ,image ,user schema
=> feat(mongoose table schema jul 8)

Backend/src/app.ts, Backend/src/controller/city_controller.ts, Backend/src/controller/hotel_controller.ts, Backend/src/domain/city_domain.ts, Backend/src/domain/hotel_domain.ts, Backend/src/statuscode.ts
merging hotel search by room count from hotel search
=> feat(hotel search by roomcount)

Backend/src/app.ts, Backend/src/controller/city_controller.ts, Backend/src/controller/hotel_controller.ts, Backend/src/domain/city_domain.ts, Backend/src/domain/hotel_domain.ts, Backend/src/statuscode.ts
get Hotel based on city and room API
=> Feat(get hotel serch api jul 11)

Backend/package.json, Backend/src/app.ts, Backend/src/controller/tour_controller.ts, Backend/src/domain/tour_domain.ts, Backend/src/model/tour.ts
=> feat(homepage_tour_api): get_tour_deatils

Backend/src/controller/hotel_controller.ts, Backend/src/domain/hotel_domain.ts
#33 Home page UI, display images based request API send image no of json
=> feat(homepage_hotel_image_api+jul_11) hotel image get api

Backend/.gitignore, Backend/package.json, Backend/src/app.ts, Backend/src/authentication/verify_token.ts, Backend/src/statuscode.ts
#50 Firebase Token Authentication and Authorization in Backend NodeTS
=> feat(authentication_backend) : introduce authentication

Backend/package.json, Backend/src/app.ts, Backend/src/controller/room_controller.ts, Backend/src/controller/user_controller.ts, Backend/src/domain/user_domain.ts, Backend/src/model/users.ts
#58 
post_user_api will post user
update_user_api will update user by uid
=> feat(post_and_update_user_api)

Backend/src/app.ts, Backend/src/authentication/verify_token.ts, Backend/src/controller/review_controller.ts, Backend/src/domain/review_domain.ts, Backend/src/model/review.ts
in this api user can post review of hotel
and get review of hotel
=> feat(post_and_get_review_api) : #57 on 14_07_2022

Backend/src/app.ts, Backend/src/controller/booking_controller.ts, Backend/src/domain/booking_domain.ts, Backend/src/model/booking.ts, Backend/src/model/users.ts, Backend/src/statuscode.ts
feat(booking_post_api) : introduce booking post api #46
=> feat(booking_post_api) : introduce booking post request

Backend/src/domain/user_domain.ts
=> feat(post_and_update_user_api) : #58 on 19-07-2022

Backend/src/domain/review_domain.ts
=> feat(post_&_get_review_api): update getHotelReview

Backend/src/controller/room_controller.ts, Backend/src/domain/room_domain.ts
add :  Get All Available Room API
=> fix(get_room_with_type_api) : #36 on 18_07_2022

Backend/package.json, Backend/src/app.ts, Backend/src/controller/booking_controller.ts, Backend/src/controller/hotel_controller.ts, Backend/src/domain/booking_domain.ts, Backend/src/domain/hotel_domain.ts, Backend/src/model/users.ts
=> feat(booking_hotel_room_avilability_check_api): introduce booking check

Backend/src/app.ts, Backend/src/controller/bookmark_controller.ts, Backend/src/domain/bookmark_domain.ts, Backend/src/model/bookmark.ts
#103 User Bookmark post, delete, and get API
=> Feat(user bookmark api):Introduce bookmark

Backend/src/controller/room_controller.ts, Backend/src/domain/room_domain.ts
#100 room_id_based_data_get_api
=> feat(room_id_based_api)

Backend/src/controller/booking_controller.ts, Backend/src/domain/booking_domain.ts
#99 introduce user booked hotel history api
=> Feat(user booking history)

Backend/src/controller/hotel_controller.ts, Backend/src/domain/hotel_domain.ts
introduce get particular hotel API
=> feat(get_particular_hotel): get perticular hotel api

Backend/package.json, Backend/src/app.ts, Backend/src/controller/booking_controller.ts, Backend/src/controller/bookmark_controller.ts, Backend/src/controller/city_controller.ts, Backend/src/controller/hotel_controller.ts, Backend/src/controller/room_controller.ts, Backend/src/controller/user_controller.ts, Backend/src/domain/booking_domain.ts, Backend/src/domain/bookmark_domain.ts, Backend/src/domain/hotel_domain.ts, Backend/src/domain/review_domain.ts, Backend/src/domain/room_domain.ts, Backend/src/domain/tour_domain.ts, Backend/src/domain/user_domain.ts, Backend/src/middlewear/logger.ts, Backend/src/statuscode.ts
=> feat(fix_backend_api) : modify some api code

Backend/src/domain/booking_domain.ts, Backend/src/domain/hotel_domain.ts, Backend/src/domain/review_domain.ts
#111  feat(fix_backend_api) : modify home screen api
=> feat(fix_backend_api) : modify home screen api

Backend/src/domain/booking_domain.ts, Backend/src/domain/payment_domain.ts
=> feat(payment freeze method):payment freeze and timeout method introduce

Backend/src/controller/booking_controller.ts, Backend/src/domain/booking_domain.ts, Backend/src/model/hotel.ts
adding mattress feature in calculation , update room category API for sold out purpose #135
=> feat(mattress_calculation_update_room_category_api): mattress calculation and update room category api 

Backend/src/controller/hotel_controller.ts, Backend/src/domain/hotel_domain.ts, Backend/src/model/users.ts
adding hotel details and delete hotel api done add image pending #142
=> feat(hotel_add_delete_api) : adding hotel details and delete hotel api done add image pending

Backend/src/app.ts, Backend/src/controller/coupon_controller.ts, Backend/src/domain/booking_domain.ts, Backend/src/domain/coupon_domain.ts, Backend/src/domain/hotel_domain.ts, Backend/src/model/booking.ts, Backend/src/model/coupon.ts
#145
get All coupon API
coupon-ID based API
coupon code-based find and validation check API
suggest coupon API
=> Feat(coupon api):introduce coupon

Backend/package.json, Backend/src/app.ts, Backend/src/controller/review_controller.ts, Backend/src/domain/review_domain.ts, Backend/src/model/review.ts, Backend/src/model/users.ts
#155 
Review moderation Introduce and review posted by a user with an image post and validation check
=> feat(review_moderation_api)

Backend/src/controller/booking_controller.ts, Backend/src/controller/hotel_controller.ts, Backend/src/domain/booking_domain.ts, Backend/src/domain/hotel_domain.ts
add roomimages & admin booking api #146
=> Feat(add roomimages booking admin api)

Backend/src/app.ts, Backend/src/domain/booking_domain.ts, Backend/src/domain/coupon_domain.ts, Backend/src/domain/payment_domain.ts, Backend/src/model/booking.ts
fix payment  & booking post api adding cors
=> Feat(fix payment  & booking post api): fix payment  & booking post api

Backend/package.json, Backend/src/app.ts, Backend/src/controller/booking_controller.ts, Backend/src/controller/cancel_booking_controller.ts, Backend/src/controller/webhook_controller.ts, Backend/src/domain/booking_domain.ts, Backend/src/domain/cancel_booking_domain.ts, Backend/src/domain/webhook_domain.ts, Backend/src/model/booking.ts, Backend/src/model/device.ts, Backend/src/statuscode.ts
#140 booking cancel api + notification
=> feat(booking_cancel_api)

Backend/src/app.ts, Backend/src/controller/device_controller.ts, Backend/src/controller/user_controller.ts, Backend/src/domain/device_domain.ts, Backend/src/domain/user_domain.ts, Backend/src/model/device.ts
adding device id api and disable user api
=> Feat(login api for deviceid) : adding device id api and disable user api

Backend/package.json, Backend/src/app.ts, Backend/src/controller/push_notification_admin_controller.ts, Backend/src/domain/push_notification_admin_domain.ts
adding post notification admin api
=> feat(push_notification_admin_api):22-08-2022 adding post notification admin #165
